//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approvisionnement
    {
        public int IdApprovisionnement { get; set; }
        public int Quantite { get; set; }
        public int IdFournisseur { get; set; }
        public int Prix { get; set; }
        public Nullable<System.DateTime> DateLivraison { get; set; }
        public int IdProduit { get; set; }
        public System.DateTime DateCommande { get; set; }
        public bool isCompleted { get; set; }
    
        public virtual Fournisseur Fournisseur { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
