//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAcces
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DAcces()
        {
            this.Fonction = new HashSet<Fonction>();
            this.User = new HashSet<User>();
        }
    
        public int IdDAcces { get; set; }
        public int isForUser { get; set; }
        public int IdACommande { get; set; }
        public int IdAFonction { get; set; }
        public int IdAPersonne { get; set; }
        public int IdAProduit { get; set; }
        public int IdASCategory { get; set; }
        public int IdACategory { get; set; }
        public int IdAFournisseur { get; set; }
    
        public virtual DACategory DACategory { get; set; }
        public virtual DACommande DACommande { get; set; }
        public virtual DAFonction DAFonction { get; set; }
        public virtual DAFournisseur DAFournisseur { get; set; }
        public virtual DAPersonne DAPersonne { get; set; }
        public virtual DAProduit DAProduit { get; set; }
        public virtual DASCategory DASCategory { get; set; }
        public virtual DAUtilisateur DAUtilisateur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fonction> Fonction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
    }
}
