//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fournisseur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fournisseur()
        {
            this.Approvisionnement = new HashSet<Approvisionnement>();
        }
    
        public int IdFournisseur { get; set; }
        public string N_Fournisseur { get; set; }
        public string C_Fournisseur { get; set; }
        public string Mail_Fournisseur { get; set; }
        public string AdresseF { get; set; }
        public string N_Telephone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Approvisionnement> Approvisionnement { get; set; }
    }
}
