//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nombre
    {
        public int IdNombre { get; set; }
        public int QuantiteF { get; set; }
        public int IdFournisseur { get; set; }
        public Nullable<System.TimeSpan> H_Livraison { get; set; }
        public Nullable<int> P_Achat { get; set; }
        public Nullable<System.DateTime> D_Livraison { get; set; }
        public int IdProduit { get; set; }
    
        public virtual Fournisseur Fournisseur { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
