//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produit()
        {
            this.Approvisionnement = new HashSet<Approvisionnement>();
            this.Vente = new HashSet<Vente>();
        }
    
        public int IdProduit { get; set; }
        public int IdSCategory { get; set; }
        public int IdUtilisateur { get; set; }
        public string NomPro { get; set; }
        public string Ref_Produit { get; set; }
        public string De_Produit { get; set; }
        public string Co_Produit { get; set; }
        public int P_NProduit { get; set; }
        public int Quantite { get; set; }
        public int Q_Critique { get; set; }
        public int Q_Fixe { get; set; }
        public bool Auto_Appro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Approvisionnement> Approvisionnement { get; set; }
        public virtual SCategory SCategory { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vente> Vente { get; set; }
    }
}
