//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int IdUtilisateur { get; set; }
        public int IdFonction { get; set; }
        public int IdPersonne { get; set; }
        public string Matricule { get; set; }
        public int Nombre { get; set; }
        public int IdDAcces { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        public virtual DAcces DAcces { get; set; }
        public virtual Fonction Fonction { get; set; }
        public virtual Person Person { get; set; }
    }
}
