//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Acces
    {
        public string Code { get; set; }
        public int IdPersonne { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public int IdUtilisateur { get; set; }
        public string Matricule { get; set; }
        public int Expr1 { get; set; }
        public string Add_Category { get; set; }
        public string Delete_Category { get; set; }
        public string Modify_Category { get; set; }
        public int IdDAcces { get; set; }
        public bool isForUser { get; set; }
        public int Expr2 { get; set; }
        public int Expr3 { get; set; }
        public int IdAFonction { get; set; }
        public string Add_Fonction { get; set; }
        public string Delete_Fonction { get; set; }
        public string Modify_Fonction { get; set; }
        public int IdAPersonne { get; set; }
        public string Add_Personne { get; set; }
        public string Delete_Personne { get; set; }
        public string Modify_Personne { get; set; }
        public int IdAProduit { get; set; }
        public string Add_Produit { get; set; }
        public string Delete_Produit { get; set; }
        public string Modify_Produit { get; set; }
        public int IdASCategory { get; set; }
        public string Add_SCategory { get; set; }
        public string Delete_SCategory { get; set; }
        public string Modify_SCategory { get; set; }
        public bool IdAUtilisateur { get; set; }
        public string Add_User { get; set; }
        public string Delete_User { get; set; }
        public string Modify_User { get; set; }
        public int IdFonction { get; set; }
        public int IdAFournisseur { get; set; }
        public string Add_Fournisseur { get; set; }
        public string Delete_Fournisseur { get; set; }
        public string Modify_Fournisseur { get; set; }
    }
}
