//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Produit
    {
        public string N_Category { get; set; }
        public string De_Category { get; set; }
        public System.DateTime D_Livraison { get; set; }
        public System.TimeSpan H_Livraison { get; set; }
        public int P_AProduit { get; set; }
        public int P_VProduit { get; set; }
        public int Quantite { get; set; }
        public string N_SCategory { get; set; }
        public string De_SCategory { get; set; }
        public string De_Produit { get; set; }
        public int IdCategory { get; set; }
        public int IdSCategory { get; set; }
        public int IdProduit { get; set; }
        public int IdFournisseur { get; set; }
        public string N_Fournisseur { get; set; }
        public string NomPro { get; set; }
    }
}
