//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_User
    {
        public int IdUtilisateur { get; set; }
        public int IdPersonne { get; set; }
        public int IdFonction { get; set; }
        public string Matricule { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public System.DateTime D_Naissance { get; set; }
        public string L_Naissance { get; set; }
        public string Adresse { get; set; }
        public string N_Telephone { get; set; }
        public string Sexe { get; set; }
        public string Code { get; set; }
        public string Libelle { get; set; }
        public string Description { get; set; }
    }
}
