//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vente
    {
        public int IdVente { get; set; }
        public int IdProduit { get; set; }
        public int IdCommande { get; set; }
        public int P_VProduit { get; set; }
        public int Qte { get; set; }
        public string Conso_Interne { get; set; }
    
        public virtual Commande Commande { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
